### ISSUE TITLE
Trouble accessing sirepo.v4.radia.run over ssh LocalForward

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#125]
I'm running Sirepo using rsconf on v4 on a remoter server. I setup an ssh LocalForward:
```
Host <redacted>
  HostName <redacted>
  Port <redacted>
  User <redacted>
  LocalForward 8080 sirepo.v4.radia.run:443
```

I get back a 404 when visiting `127.0.0.1:8080`. 

It works if I change my /etc/hosts to be:
```
127.0.0.1	localhost localhost.localdomain sirepo.v4.radia.run
```

Our nginx conf looks at the host header to determine how to route the request. So, when the host is `127.0.0.1` then it routes to 404 instead of Sirepo. Maybe we change the nginx conf or maybe just stick with manually editing /etc/hosts?

**Comment by robnagler** [comment]
I forgot about this step. There's no way around this if you are using nginx.conf, because it will route on host, since there might be multiple services being routed, e.g. job-supervisor. rsconf may configure other hosts (owncloud), too.

Note that you will have to undo this if you are using a local v4.radia.run.

**Comment by e-carlin** [comment]
Ok, thanks. I update our [development wiki](https://github.com/radiasoft/rsconf/wiki/Development#port-forwarding) with instructions.
