### ISSUE TITLE
Fix package_data/dev/db/* to conform to fconf default

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#215]
With fconf now being the default (#214) we should change the example data to use it.

@robnagler agree? Can you assign a milestone?

**Comment by robnagler** [comment]
This can't be changed, because it is jinja generating fconf. The result is actually not fconf, but just straight yaml. I think it would be confusing (and possibly impossible) to generate fconf in fconf.

However, there is a bug now that the defaults have been changed, which I'll use this issue to have fixed:

 key=nameservers type mismatch between (self) base=['162.159.27.72', '162.159.24.39'] and to_merge={'RSCONF_DB\
_REPLACE': ['1.1.1.1', '1.0.0.1']}

**Comment by e-carlin** [comment]
> The result is actually not fconf, but just straight yaml

I see now. Thanks.

> there is a bug now that the defaults have been changed, which I'll use this issue to have fixed

How would you like this solved? Augment pkmerge so it is aware of a "replacement_key" (in this case RSCONF_DB_REPLACE)?

**Comment by robnagler** [comment]
We don't need RCONF_DB_REPLACE. I removed it in prod so it isn't needed in the dev data, which was just there to test that it worked. It could be replaced completely.
