### ISSUE TITLE
tests failing on master

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#280]
This is blocking my pr https://github.com/radiasoft/rsconf/actions/runs/3569650206/jobs/5999811224

I can reproduce on my machine. According to GH tests passed for the most recent commit (or at least that is what I think the green checkmark next to the commit means). Not sure what's going on...

**Comment by e-carlin** [comment]
@robnagler expected time is 12:30:0 actual time is 13:30:0 in db_bkp.timer. My best guess is this is a DST problem. I see mention of DST for generating the on_calendar https://github.com/radiasoft/rsconf/blob/cf962d1f7d48c8385ece968959976260b8a1552f/rsconf/systemd.py#L283 . I don't exactly understand what all of that code is doing. Any idea what's going on?

**Comment by robnagler** [comment]
This is why we need fuzzy testing. It would be nice to figure out how to do this in a clever way. For now, you can update the data, making sure the differences are just the times.

Systemd does not support timezone configuration in the unit files until after the version used in CentOS 7. The servers run in UTC. Things like backups, test suites, etc. run in specific time zones. Therefore, we set the time zone in rsconf and when we generate the unit files, we convert the times (which are written in local time) to UTC (which takes into account DST). The fix for this is always to output non-DST and have a shim that delays the actual start by an hour based on the configured time zone (#16). For now, we simply run rsconf build and push to all machines that matter (not all hosts, which only do log rotation at a specific systemd time).

You could also bump #16 as a priority before next DST change. :)

**Comment by e-carlin** [comment]
Ah, thanks for the explanation.
