### ISSUE TITLE
main.sh.jinja's need `set -e`

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#520]
I had a bug in my changes but rsc didn't blow up
```
Source: /var/tmp/radia-run-17302-27777/20240801164924-docker.sh
/srv/docker/volumes: exists, docker already installed
bash: line 51: docker_need_update: command not found
curl -L -s -S -n http://v3.radia.run:2916/host/v3.radia.run//etc/docker/certs.d/v3.radia.run:5000/ca.crt
```

Looks like none of our main.sh.jinja's have set -e (or ou pipefail). @robnagler why is that? Should it come from somewhere outside?

**Comment by robnagler** [comment]
An `if` statement overrides `-e`, since `-e` is simply testing that any command returns non-zero, which is what `if` does. There is no concept of an exception or error in Bash. This is why tests are important, I think, but that's not easy to do for this type of code without a lot of mocking, which reduces the quality of the tests. I would say this is simply a consequence of programming in Bash, and why we do as little of it as possible in rsconf, and rely on Python for the heavy lifting.

**Comment by e-carlin** [comment]
Ah of course. Thank you. 

FWIW - came across this interesting shellcheck https://www.shellcheck.net/wiki/SC2155 . Maybe something we should add to our style.
